version: '3.7'
services:
  yukisarcasmdetect:
    container: 'yukisarcasmdetect'
    image: 'yukisarcasmdetect:sarcasm'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/sarcasm'
      - '/sarcasm/node_modules'
      - '/sarcasm/package.json'
    ports:
      - '3000:3000'
    restart: on-failure
    command: 'npm start'
